import TemplateOne from "@app/template/layout_1/Template_one ";
import Head from "next/head";
import styled from "styled-components";
import Container from "./components/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container background="#181818">
        <TemplateOne />
      </Container>
    </>
  );
}
